name: "Check bypass"
description: "A custom action to encapsulate PFCCLab/ci-bypass"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  workflow-name:
    description: "Workflow name"
    required: true
outputs:
  can-skip:
    description: "Whether the workflow can be skipped."
    value: ${{ steps.check-bypass.outputs.can-skip }}

runs:
  using: "composite"
  steps:
    - id: check-bypass
      name: Check Bypass
      env:
        CI_TEAM_MEMBERS: '["tianshuo78520a", "swgu98", "risemeup1", "XieYunshen","luotao1","From00"]'
      uses: PFCCLab/ci-bypass@v1
      with:
        github-token: ${{ inputs.github-token }}
        non-pull-request-event-strategy: 'never-skipped'
        type: 'composite'
        composite-rule: |
          {
            "any": [
              {
                "type": "labeled",
                "label": ["skip-ci: ${{ inputs.workflow-name }}", "skip-ci: all"],
                "username": ${{ env.CI_TEAM_MEMBERS }}
              },
              {
                "type": "commented",
                "comment-pattern": [".*/skip-ci ${{ inputs.workflow-name }}.*", ".*/skip-ci all.*"],
                "username": ${{ env.CI_TEAM_MEMBERS }}
              }
            ]
          }
